name: DCO check
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  dco_check_job:
    runs-on: ubuntu-latest
    name: DCO Check
    steps:
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: DCO Check
      uses: tim-actions/dco@master
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
    - name: DCO comment
      if: failure()
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          var msg = `Oops! Looks like you failed the \`DCO check\`. Be sure to sign all your commits.

          ### Howto

          - [Magma guidelines on signing commits](https://magma.github.io/magma/docs/next/contributing/contribute_workflow#guidelines)
          - [GitHub documentation on signing commits](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification)`

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: msg,
          })
